name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World!"
      - name: "Minha segunda ação"
        run: |
          echo "Você criou a sua primeira pipeline!"
          echo "Parabéns!"
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
      - name: "Definição da versão 22.21.0 do NodeJs"
        uses: actions/setup-node@v6
        with:
          node-version: '22.21.0'
      - name: "Verificação da versão do NodeJS depois de instalar"
        run: node --version
